### ISSUE TITLE
[1] Tribler crashes: "Unknown version found"

### ISSUE THREAD

**Issue by rkeulemans** [vandenheuvel/tribler#323]
After running Tribler for ~10 minutes it crashes:
```
ERROR:root:Traceback (most recent call last):
  File "/home/ruben/git_projects/tribler/TriblerGUI/event_request_manager.py", line 99, in on_read_data
    raise RuntimeError(json_dict["event"]["text"])
RuntimeError: Unhandled Error
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ruben/git_projects/tribler/TriblerGUI/core_manager.py", line 63, in start_tribler_core
    reactor.run()
  File "/usr/lib/python2.7/site-packages/twisted/internet/base.py", line 1243, in run
    self.mainLoop()
  File "/usr/lib/python2.7/site-packages/twisted/internet/base.py", line 1252, in mainLoop
    self.runUntilCurrent()
--- <exception caught here> ---
  File "/usr/lib/python2.7/site-packages/twisted/internet/base.py", line 851, in runUntilCurrent
    f(*a, **kw)
  File "/home/ruben/git_projects/tribler/Tribler/dispersy/endpoint.py", line 253, in dispersythread_data_came_in
    u"standalone_ep")
  File "/home/ruben/git_projects/tribler/Tribler/dispersy/dispersy.py", line 1489, in on_incoming_packets
    community.on_incoming_packets(list(iterator), cache, timestamp, source)
  File "/home/ruben/git_projects/tribler/Tribler/dispersy/community.py", line 2022, in on_incoming_packets
    self._on_batch_cache(meta, batch)
  File "/home/ruben/git_projects/tribler/Tribler/dispersy/community.py", line 2079, in _on_batch_cache
    messages.append(conversion.decode_message(candidate, packet, source=source))
  File "/home/ruben/git_projects/tribler/Tribler/dispersy/util.py", line 150, in wrapper
    return_value = func(*args, **kargs)
  File "/home/ruben/git_projects/tribler/Tribler/dispersy/conversion.py", line 1219, in decode_message
    placeholder.offset, placeholder.payload = decode_functions.payload(placeholder, placeholder.offset, payload)
  File "/home/ruben/git_projects/tribler/Tribler/community/trustchain/conversion.py", line 52, in _decode_half_block
    block = TrustChainBlock.unpack(data, offset)
  File "/home/ruben/git_projects/tribler/Tribler/community/trustchain/block.py", line 308, in unpack
    _, ret.transaction = decode(data[offset:offset + tx_len])
  File "/home/ruben/git_projects/tribler/Tribler/Core/Utilities/encoding.py", line 339, in decode
    raise ValueError("Unknown version found")
exceptions.ValueError: Unknown version found
```

**Comment by ghabbenjansen** [comment]
This crash looks a lot like the same crash that occurs when you run the crawler
